### ISSUE TITLE
Please share schematic V3.1

### ISSUE THREAD

**Issue by qrp73** [hugen79/NanoVNA-H#10]
Could you please share schematic for PCB rev V3.1? 
The schematic in the doc folder is V3.3, but my NanoVNA-H has PCB V3.1.
Thanks

**Comment by hugen79** [comment]
Sorry, I have only checked the information about GitHub today because of the troublesome work I have recently. The schematics of V3.1 and V3.3 are the same, only R41 and R42 are missing. I am preparing to update the PCB to V3.4. If you wish, you can send your address to my email at hugen@outlook.com and I will send you the modified PCB. Thank you!
