### ISSUE TITLE
Reload FW after uploading wrong version

### ISSUE THREAD

**Issue by DABtester** [hugen79/NanoVNA-H#57]
Accidently i uploaded the H4 firmware, and now my device is bricked.
Any way to un-brick it again / upload the correct version?

Thanks

**Comment by Pmax65** [comment]
Hi DABtester.
Since the device is hanged-up now, you must turn on the board while short-cutting the two P1 pins named Boot and VDD to start the DFU mode.

Have a great day.

Massimo - IK1IZA

**Comment by benner** [comment]
IIRC it can be done by holding some buttons when powering up  too

**Comment by Pmax65** [comment]
Hi benner,
> IIRC it can be done by holding some buttons when powering up too
That depends upon the previously uploaded firmware. He got the hardware hanged up by a wrong firmware upload, it shouldn't work because the device is locked somewhere unknown in the code.
The P1 short-cutting is embedded in the bootstrap code and it should be always available independently by downloaded firmware.

Have a great day.

Massimo - IK1IZA

**Comment by DABtester** [comment]
> Hi DABtester.
> Since the device is hanged-up now, you must turn on the board while short-cutting the two P1 pins named Boot and VDD to start the DFU mode.
> 
> Have a great day.
> 
> Massimo - IK1IZA

That worked - many thanks for your help!

**Comment by Pmax65** [comment]
Nice to be helpful to you.

Have a great day.

Massimo
